apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-run-cymbal
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-cymbal-dev
    profiles: [dev]
  - targetId: run-cymbal-prod
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-cymbal-dev
description: Cloud Run development service
run:
  location: projects/idoflatow-dotnet-demo-2/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-cymbal-prod
description: Cloud Run production service
run:
  location: projects/idoflatow-dotnet-demo-2/locations/us-central1
