steps:
# Docker Build on Cloud Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/cymbal-coffee/cymbalcoffee:$SHORT_SHA', '.']
 
# Docker Push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/cymbal-coffee/cymbalcoffee:$SHORT_SHA'] 

# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      'deploy', 'releases', 'create', 'rel-${SHORT_SHA}',
      '--delivery-pipeline', 'my-run-cymbal',
<<<<<<< HEAD
      '--region', '$LOCATION',
      '--source', 'deploy-run-cymbal/',
=======
      '--region', 'us-central1',
>>>>>>> 88c665806ada92f171c7d413d9a04f62a827ba20
      '--annotations', 'commitId=${REVISION_ID}',
      '--images', 'my-app-image=$LOCATION-docker.pkg.dev/$PROJECT_ID/cymbal-coffee/cymbalcoffee:$SHORT_SHA'
    ]
