apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-cymbal-prod
spec:
  template:
    spec:
      containers:
      - image: my-app-image
        ports:
          - name: http1
            containerPort: 80
